#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./err/tjob.out.%j
#SBATCH -e ./err/tjob.err.%j
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J pp_Z46
# Queue (Partition):
#SBATCH --partition=express
# Number of nodes and MPI tasks per node:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#
#SBATCH --mail-type=none
#SBATCH --mail-user=phess@rzg.mpg.de
#
# Wall clock limit:
#SBATCH --time=00:30:00

# Run the program:
srun ./run < param/Z46.dat
