#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./err/tjob.out.%j
#SBATCH -e ./err/tjob.err.%j
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J pp_V41
# Queue (Partition):
#SBATCH --partition=short
# Number of nodes and MPI tasks per node:
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=32
#
#SBATCH --mail-type=none
#SBATCH --mail-user=phess@rzg.mpg.de
#
# Wall clock limit:
#SBATCH --time=03:00:00

# Run the program:
srun ./run < param/V41.dat
